puts "🌱 Seeding spices..."

china = Country.create(name: "China" , population: 1425887337)
india = Country.create(name: "India", population: 1417173173)
indonesia = Country.create(name: "Indonesia" , population: 275501339)
pakistan = Country.create(name: "Pakistan" , population: 235824862)
bangladesh = Country.create(name: "Bangladesh" , population: 171186372)
japan = Country.create(name: "Japan" , population: 123951692)
philippines = Country.create(name: "Philippines", population: 115559009)
vietnam = Country.create(name: "Vietnam" , population: 98186856)
iran = Country.create(name: "Iran" , population: 88550570)
turkey = Country.create(name: "Turkey" , population: 85341241)
thailand = Country.create(name: "Thailand", population: 71697030)
myanmar = Country.create(name: "Myanmar" , population: 54179306)
south_korea = Country.create(name: "South Korea" , population: 51815810)
iraq = Country.create(name: "Iraq" , population: 44496122)
afghanistan = Country.create(name: "Afghanistan", population: 41128771)
saudi_arabia = Country.create(name: "Saudi Arabia", population: 36408820)
uzbekistan = Country.create(name: "Uzbekistan", population: 34627652)
malaysia = Country.create(name: "Malaysia", population: 33938221)
yemen = Country.create(name: "Yemen", population: 33696614)
nepal = Country.create(name: "Nepal", population: 30547580)
north_korea = Country.create(name: "North Korea" , population: 26069416)
syria = Country.create(name: "Syria", population: 22125249)
sri_lanka = Country.create(name: "Sri Lanka", population: 21832143)
kazakhstan = Country.create(name: "Kazakhstan", population: 19397998)
cambodia = Country.create(name: "Cambodia", population: 16767842)
jordan = Country.create(name: "Jordan", population: 11285869)
azerbaijan = Country.create(name: "Azerbaijan" , population: 10358074)
tajikistan = Country.create(name: "Tajiskistan", population: 9952787)
uae = Country.create(name: "United Arab Emirates", population: 9441129)
israel = Country.create(name: "Israel", population: 9038309)
laos = Country.create(name: "Laos", population: 7529475)
kyrgyzstan = Country.create(name: "Kyrgyzstan", population: 6630623)
turkmenistan = Country.create(name: "Turkmenistan", population: 6430770)
singapore = Country.create(name: "Singapore", population: 5975689)
lebanon = Country.create(name: "Lebanon", population: 5489739)
palestine = Country.create(name: "Palestine", population: 5250072)
oman = Country.create(name: "Oman", population: 4576298)
kuwait = Country.create(name: "Kuwait", population: 4268873)
georgia = Country.create(name: "Georgia", population: 3744385)
mongolia = Country.create(name: "Mongolia", population: 3398366)
armenia = Country.create(name: "Armenia", population: 2780469)
qatar = Country.create(name: "Qatar", population: 2695122)
bahrain = Country.create(name: "Bahrain", population: 1472233)
timor_leste= Country.create(name: "Timor-Leste", population: 1341296)
cyprus = Country.create(name: "Cyprus", population: 1207359)
bhutan = Country.create(name: "Bhutan", population: 782455)
maldives = Country.create(name: "Maldives", population: 523787)
brunei = Country.create(name: "Brunei", population: 449002)

puts "✅ Done seeding!"

Attraction.create(name: "Babur Tomb", image_url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/08/96/fb/shah-jahan-mosque.jpg?w=1200&h=-1&s=1", description: "The Garden of Babur is a historic park in Kabul, Afghanistan, and also has the tomb of the first Mughal emperor Babur. The garden is thought to have been developed around 1528, when Babur gave orders for the construction of an avenue garden in Kabul, described in some detail in his memoirs, the Baburnama.", country_id: afghanistan.id)

Food.create(name: "Kabuli Palau", image_url: "https://afghancooks.com/wp-content/uploads/2021/09/IMG_0858_jpg.jpg", description: "Kabuli Palau (Also known as Quaboli Palaw, Qabili Palau or Palao, Palaw, Pilau or Pilaf, and Qabili/Kabuli Palau) is a popular meal in Afghanistan. It is a mixed rice dish containing flavorful lamb or chicken chunks, carrot strips, raisins, and eastern spices. It is traditionally topped with chopped almonds or pistachios.", country_id: afghanistan.id)